name: Deploy CloudFormation Stack
on:
  push:
    branches:
      - master
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Cache inastaller files
        uses: actions/cache@v1
        with:
          path: aws_install
          key: ${{ runner.OS }}-deploy
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: Download AWS client installer
        run: |
          [ -d aws_install ] || ( curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o temp.zip && unzip temp.zip -d aws_install && rm temp.zip )
      - name: Setup AWS client
        run: sudo aws_install/aws/install
  package:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm install
      - name: Build
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
        run: gulp
      - name: Upload code pacakge
        uses: actions/upload-artifact@v1
        with:
          name: lambda-zip
          path: build/lambda.zip
      - name: Upload code version
        uses: actions/upload-artifact@v1
        with:
          name: lambda-version
          path: build/.version
  deploy:
    needs:
      - setup
      - package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/download-artifact@v1
        with:
          name: lambda-zip
          path: build/lambda.zip
      - uses: actions/download-artifact@v1
        with:
          name: lambda-version
          path: build/.version
      - name: Deploy stack
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
          AWS_DEFAULT_REGION: ${{ secrets.aws_default_region }}
        run: aws cloudformation deploy --template-file "./election-app.yaml" --stack-name odileeds-uk-election-2019 --s3-bucket odileeds-code-staging --s3-prefix election-2019 --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset --parameter-overrides CodeVersion=$(cat build/.version)
