name: Deploy CloudFormation Stack
on:
  push:
    branches:
      - master
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup AWS
        run: |
          curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
  deploy:
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Deploy stack
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.aws_access_key_id }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.aws_secret_access_key }}
          AWS_DEFAULT_REGION: ${{ secrets.aws_default_region }}
        run: aws cloudformation deploy --template-file "./election-app.yaml" --stack-name odileeds-uk-election-2019 --s3-bucket odileeds-code-staging --s3-prefix election-2019 --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset
